# Generated by Django 5.2.8 on 2025-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
