# Generated by Django 5.2.8 on 2025-11-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_status_remove_orderitem_product_and_more'),
        ('products', '0002_remove_productimage_product_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='replace_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='replace_product_sku',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
