# Generated by Django 5.2.8 on 2025-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productimage_product_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
